name: Compare Repos

on:
  workflow_dispatch

jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.9
      - name: Install dependencies
        run: go get -v -t -d ./...
      - name: Build
        run: go build -v .
        env:
          GH_ORG_NAME: ${{ secrets.GH_ORG_NAME }}
          GHEC_ACCESS_TOKEN: ${{ secrets.GHEC_ACCESS_TOKEN }}
          GITLAB_ACCESS_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
          GL_PROJECT_ID: ${{ secrets.GL_PROJECT_ID }}
      - name: Run
        run: go run main.go
        env:
          GH_ORG_NAME: ${{ secrets.GH_ORG_NAME }}
          GHEC_ACCESS_TOKEN: ${{ secrets.GHEC_ACCESS_TOKEN }}
          GITLAB_ACCESS_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
          GL_PROJECT_ID: ${{ secrets.GL_PROJECT_ID }}