name: Compare Repos

on:
  issues:
    types: [labeled]
    

jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - if : github.event.label.name == 'kpi'
        name: Compare Repos
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          org: "pernod-ricard-mmpj"
          file: ./source.json