name: Run Migration

on: workflow_dispatch

steps:
  # Check out the code and install dependencies
  - name: Check out code
    uses: actions/checkout@v2
  - name: Install dependencies
    run: go get -v ./...

  # Build and run the Golang app
  - name: Build and run Golang app
    env:
    run: go run main.go ${{ secrets.GHEC_ACCESS_TOKEN }} ${{ secrets.GITLAB_ACCESS_TOKEN }} ${{ secrets.GH_ORG_NAME }} ${{ secrets.GL_PROJECT_ID }}

  # Create an issue with the output of the app
  - name: Create issue with output
    uses: appleboy/github-script@v1
    with:
      script: |
        issue = context.issue({
          title: 'Migration Stats',
          body: cat('output.md'),
          labels: ['migration-kpi', 'gitlab']
        })
        context.github.issues.create(issue)
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
